# Use postgres/example user/password credentials

services:

  db:
    image: sdl/postgres:ru
    restart: always
    shm_size: 128mb
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_PASSWORD: password1234
    ports:
      - 5433:5432


  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  app:
    image: dpps-app7:2.1
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: my_app
    stdin_open: true
    tty: true
    env_file:
      - .env
    environment:
      LOG_USER_FILE_PATH: ${LOG_USER_FILE_PATH}
      LOG_FULL_FILE_PATH: ${LOG_FULL_FILE_PATH}
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: software_company_db
      FLASK_ENV: production
      SESSION_TIMEOUT_MINUTES: 10
      APP_SECRET_KEY: dpps-dev-secret
    volumes:
      - ../logs:/app/logs
    ports:
      - 5000:5000
    depends_on:
      - db